[package]
name = "logan_kmer_spectrum"
version = "0.1.0"
edition = "2021"

#![feature(diagnostic_namespace)]

[dependencies]
bio = "2.0.3"
clap = { version = "4.4", features = ["derive"] }
regex = "1.10"
zstd = "0.13"
